// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOM2l4DDTotQVBABSf7arniqGN8lk4qSw',
    appId: '1:828296953658:android:c19854f28821d877cf9a03',
    messagingSenderId: '828296953658',
    projectId: 'bellybloom-f895a',
    databaseURL: 'https://bellybloom-f895a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bellybloom-f895a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOTHjDEJ6UNIrsrWP_DIVgABgDeFJSK1E',
    appId: '1:828296953658:ios:6913f886231f145ecf9a03',
    messagingSenderId: '828296953658',
    projectId: 'bellybloom-f895a',
    databaseURL: 'https://bellybloom-f895a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bellybloom-f895a.firebasestorage.app',
    iosBundleId: 'com.example.bellyBloom',
  );
}
